### PR TITLE
FoundationOwner to Registry Contract

### PR DESCRIPTION
**Pull request by ksridharbabuus**
Added foundation owner to the registry with authorization on delete functionality (Org, Service, TypeRepo and Tags).

### CODE REVIEW

**Comment by astroseger** [comment]
In general looks good for me.
Two comments.
1. I would add possibility to change foundationOwner just in case. But it is more question to "users" @pennachin: do we need possibility to change foundationOwner? 

2. In tests there is a small "bug". Registry have foundationOwner=account[0], but your organization has owner=account[0] (it has member=account[1], but owner is still account[0]). So you don't really test foundationOwner logic.   You should create organization with "{from=account[2]}, for example".

3. I would propose to add tests that not foundation member (and not the owner/member of the organization) cannot run delete functions. In test/MultiPartyEscrow_test1.js there is a function testErrorRevert which can be useful for such tests.

**Comment by ksridharbabuus** [comment]
@astroseger 
1. I dont see the need to add the function as this is only a fallback option, but if needed we can add a function to update the foundationOwner
2. Updated the test cases to use accounts[1] for all the creations. Copy paste mistake from previous test case :(
3. Added negative test cases as well

**Comment by astroseger** [comment]
Seems good for me (from algorithmic point of view). But I propose to wait answer from @pennachin (do we need function for update the foundationOwner or not?)... And comments from @tiero.

**Comment by ksridharbabuus** [comment]
@astroseger Yes will wait for their comments before merging the changes. Thanks!

**Comment by ferrouswheel** [comment]
Can we change the name of the user? Please see https://github.com/singnet/platform-contracts/issues/88#issuecomment-455323049 for why.

**Comment by pennachin** [comment]
It would be good to have a generic name like "owner" or some such, because the curation process isn't related to this spam cleaning ability.  Answering @astroseger I don't think we need to support changing the owner.

**Comment by raamb** [comment]
We are not making this change now

**Pull request closed without merging**
