### PR TITLE
Updated Registry Contract for Efficiency

### PR DESCRIPTION
**Pull request by ksridharbabuus**
Removed following Items:
Tags
TypeRepos

### CODE REVIEW

**Review by raamb — APPROVED** [review]

**Review by astroseger — COMMENTED** [review]
With a big number of services and members, deleteOrganization would require a lot of gas and potentially might fail. But it seems we don’t need to manually delete all services and members. We simply could put orgsById[orgId]  to 0 (just to make sure that old OrganizationRegistration would be lost forever) and remove it from orgKeys. This would save a lot of gas.


I would propose to consider splitting requireAuthorization into requireAuthorizationOwner and requireAuthorizationOwnerOrMember. It would make the logic a little bit more clearer. This might also save a little bit of gas. The same story with requireOrgExistenceConstraint (split into requireOrgExistence and requireOrgNonExistence), and requireServiceExistenceConstraint (split into  requireServiceExistence and requireServiceNonExistence). 


We don’t have the special function for adding a single member to the organization, only addOrganizationMembers. Such a special function might be slightly more gas efficient (for adding a single member). But I’m not sure if it is worth introducing such a function. It depends on how frequent the use case will be for adding a single member to the organization and how significant would be the gas saving. 


If gas cost is a very significant issue then we might consider switching to a model in which we do not remove deleted services and organizations from serviceKeys and orgKeys. In order to delete service we simply put servicesById[serviceId] to 0, and do not modify serviceKeys. Offchain function will need to filter services with 0 servicesById[serviceId]  after calling listServicesForOrganization.

**Comment by ksridharbabuus** [comment]
@astroseger 
Agree with you that the Deletion of Organization Gas cost is going to be directly proportionate to the number of services associated with the Organization. I don't think we can assign an empty structure or zero or even a flag (isDeleted/isActive) as the consumers of the Registry can be a anyone beyond us. Will be difficult to provide the instructions on which org is deleted or active...

Agree that the Splitting of the Gaurd functions might be more readable, I prefer to convert it to Modifers in the contract rather than splitting. But I don't see any difference in the overall execution point of view so left it as is.

Will create the issue based on this review comments and will take it up in the next opportunity to modify the registry contract.

**Comment by astroseger** [comment]
> @astroseger
> Agree with you that the Deletion of Organization Gas cost is going to be directly proportionate to the number of services associated with the Organization. I don't think we can assign an empty structure or zero or even a flag (isDeleted/isActive) as the consumers of the Registry can be a anyone beyond us. Will be difficult to provide the instructions on which org is deleted or active...
> 

But my first proposition is actually independent of my fourth proposition in which I proposed to change the way in which we deal with deleted organizations and services. My first proposition was more simple: It seems, in deleteOrganization we don't really need to delete all members and remove all services. We could simply remove orgId from orgsKeys (and from orgsById). In this case the logic (including off-chain) will be exactly the same.

**Comment by ksridharbabuus** [comment]
@astroseger 
Yes we can but it will make the contract with lots of orphan content.
As per the current usage we don't see too many delete operations. 
Thinking that we can go with it for now and we can definitely decide based on the usage metrics in the future.

**Comment by astroseger** [comment]
> @astroseger
> Yes we can but it will make the contract with lots of orphan content.
> As per the current usage we don't see too many delete operations.
> Thinking that we can go with it for now and we can definitely decide based on the usage metrics in the future.

But why it is an orphan content? All links to this content will be lost, and "storing" this content will be free for us in any case. But deleting will cost us gas.

**Comment by ksridharbabuus** [comment]
@astroseger 
Since only the links to content is lost and the content is no more in use. But it is still reachable through the OrgIds.
If you look at the Gas Cost in deleting & updating the Service is pretty low. So we can leave the responsibility to the Org Owner to manage it.

**Comment by astroseger** [comment]
> @astroseger
> Since only the links to content is lost and the content is no more in use. But it is still reachable through the OrgIds.
> If you look at the Gas Cost in deleting & updating the Service is pretty low. So we can leave the responsibility to the Org Owner to manage it.

(probably it is too late but just for conclude the discussion)
I think if we set orgsById[OrgId] to 0 and then remove OrgId from orgKeys, then it cannot be reached thought OrgIds. But I agree that it is not very important especially if we don't have much time now.

**Pull request merged**
