### PR TITLE
add nonce to events

### PR DESCRIPTION
**Pull request by astroseger**
This pull request add nonce to events.

1. I'm not sure that we need nonce in ChannelOpen event because it is always 0... 
2. Probably we should rearrange order of variables inside struct PaymentChannel (and maybe inside events also) to make it more logical..

### CODE REVIEW

**Comment by tiero** [comment]
Watch out, there is a regression with the `keepAmpount` typo

For the 2, I agree. It's not logical increment the nonce inside the branch check and other time inside the sendBack function. Would be nice to do in the same place

**Comment by astroseger** [comment]
@tiero @ksridharbabuus 
I've added two changes.

1. I've changed order of fields inside "struct PaymentChannel" and "event ChannelOpen" in order to make order in "struct PaymentChanel" and all events consistent (channelId, nonce,sender,  signer, recipient,groupId,amount,expiration ). Normally it is not an API change, so it should be ok. Do you agree?
2. I've added "event DepositFunds" and "event WithdrawFunds". I think we need them. 

It would be nice to change order of arguments in openChannel function (to have consistence order). But it is an API change, so probably we shoudn't do it.

**Comment by tiero** [comment]
Agree with changes.
I would prefer to change it now before major release

**Comment by ksridharbabuus** [comment]
I agree with the changes.

We need to make sure that the calls to contract to return channel details
in the client side has an impact, needs to modify in case if they are
directly assigning to group of variables.

**Pull request merged**
